# CI de nível 01 - Disparo manual a partir de 1 clique

# Nome que vai aparecer nas opções da pipe
name: 'Execução Manual'

#triggers ou gatlhos de execução 
# gatilho de exec manual = workflow_dispatch

# on:
#     workflow_dispatch:

# jobs:
#   biuld:
#     steps:
#     - baixar as deps
#     - subir a aplicação
#     - gerar a versão
  
#   tests:
#     if: (build = sucesso; então pode proceguir)
#     steps:
#       - instalar as deps
#       - executar o comando para rodar os testes

#on é onde configuramos as regras de disparos
on: 
  workflow_dispatch

jobs:
  #descrição do job
  e2e-tests:
    #maquina que o jo vai execcutar
    runs-on ['umutu-latest']
    #passo a passo das ações do job
    steps:
      - uses: actions/checkout@v4
      # - uses? actions/setup-node@v4
      #   with:
      #   node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando depêndencias
        run: yarn
      
      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e